name: example-ci

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install cowsay Program
              run: sudo apt-get install cowsay -y
            - name: Execute cowsay CMD
              run: cowsay -f dragon "Runn for cover, I am Dragon" >> dragon.txt
            - name: show files
              run: cat dragon.txt
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: show file
              run: cat dragon.txt